/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(smart_environment_DeviceState, smart_environment_DeviceState, AUTO)


PB_BIND(smart_environment_LuminosityData, smart_environment_LuminosityData, AUTO)


PB_BIND(smart_environment_DistanceData, smart_environment_DistanceData, AUTO)









