/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SMART_ENVIRONMENT_MESSAGES_PB_H_INCLUDED
#define PB_SMART_ENVIRONMENT_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Device type enumeration */
typedef enum _smart_environment_DeviceType {
    smart_environment_DeviceType_UNKNOWN = 0,
    smart_environment_DeviceType_LUMINOSITY_SENSOR = 1,
    smart_environment_DeviceType_DISTANCE_SENSOR = 2
} smart_environment_DeviceType;

typedef enum _smart_environment_LuminosityData_State {
    smart_environment_LuminosityData_State_UNKNOWN = 0,
    smart_environment_LuminosityData_State_DARK = 1,
    smart_environment_LuminosityData_State_DIM = 2,
    smart_environment_LuminosityData_State_BRIGHT = 3
} smart_environment_LuminosityData_State;

typedef enum _smart_environment_DistanceData_State {
    smart_environment_DistanceData_State_UNKNOWN = 0,
    smart_environment_DistanceData_State_CLOSE = 1,
    smart_environment_DistanceData_State_MEDIUM = 2,
    smart_environment_DistanceData_State_FAR = 3
} smart_environment_DistanceData_State;

/* Struct definitions */
/* Luminosity sensor data */
typedef struct _smart_environment_LuminosityData {
    uint32_t raw_value;
    smart_environment_LuminosityData_State state;
} smart_environment_LuminosityData;

/* Distance sensor data */
typedef struct _smart_environment_DistanceData {
    uint32_t distance_cm;
    smart_environment_DistanceData_State state;
} smart_environment_DistanceData;

/* Device state message */
typedef struct _smart_environment_DeviceState {
    pb_callback_t device_id;
    smart_environment_DeviceType type;
    pb_size_t which_sensor_data;
    union {
        smart_environment_LuminosityData luminosity;
        smart_environment_DistanceData distance;
    } sensor_data;
} smart_environment_DeviceState;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _smart_environment_DeviceType_MIN smart_environment_DeviceType_UNKNOWN
#define _smart_environment_DeviceType_MAX smart_environment_DeviceType_DISTANCE_SENSOR
#define _smart_environment_DeviceType_ARRAYSIZE ((smart_environment_DeviceType)(smart_environment_DeviceType_DISTANCE_SENSOR+1))

#define _smart_environment_LuminosityData_State_MIN smart_environment_LuminosityData_State_UNKNOWN
#define _smart_environment_LuminosityData_State_MAX smart_environment_LuminosityData_State_BRIGHT
#define _smart_environment_LuminosityData_State_ARRAYSIZE ((smart_environment_LuminosityData_State)(smart_environment_LuminosityData_State_BRIGHT+1))

#define _smart_environment_DistanceData_State_MIN smart_environment_DistanceData_State_UNKNOWN
#define _smart_environment_DistanceData_State_MAX smart_environment_DistanceData_State_FAR
#define _smart_environment_DistanceData_State_ARRAYSIZE ((smart_environment_DistanceData_State)(smart_environment_DistanceData_State_FAR+1))

#define smart_environment_DeviceState_type_ENUMTYPE smart_environment_DeviceType

#define smart_environment_LuminosityData_state_ENUMTYPE smart_environment_LuminosityData_State

#define smart_environment_DistanceData_state_ENUMTYPE smart_environment_DistanceData_State


/* Initializer values for message structs */
#define smart_environment_DeviceState_init_default {{{NULL}, NULL}, _smart_environment_DeviceType_MIN, 0, {smart_environment_LuminosityData_init_default}}
#define smart_environment_LuminosityData_init_default {0, _smart_environment_LuminosityData_State_MIN}
#define smart_environment_DistanceData_init_default {0, _smart_environment_DistanceData_State_MIN}
#define smart_environment_DeviceState_init_zero  {{{NULL}, NULL}, _smart_environment_DeviceType_MIN, 0, {smart_environment_LuminosityData_init_zero}}
#define smart_environment_LuminosityData_init_zero {0, _smart_environment_LuminosityData_State_MIN}
#define smart_environment_DistanceData_init_zero {0, _smart_environment_DistanceData_State_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define smart_environment_LuminosityData_raw_value_tag 1
#define smart_environment_LuminosityData_state_tag 2
#define smart_environment_DistanceData_distance_cm_tag 1
#define smart_environment_DistanceData_state_tag 2
#define smart_environment_DeviceState_device_id_tag 1
#define smart_environment_DeviceState_type_tag   2
#define smart_environment_DeviceState_luminosity_tag 3
#define smart_environment_DeviceState_distance_tag 4

/* Struct field encoding specification for nanopb */
#define smart_environment_DeviceState_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (sensor_data,luminosity,sensor_data.luminosity),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (sensor_data,distance,sensor_data.distance),   4)
#define smart_environment_DeviceState_CALLBACK pb_default_field_callback
#define smart_environment_DeviceState_DEFAULT NULL
#define smart_environment_DeviceState_sensor_data_luminosity_MSGTYPE smart_environment_LuminosityData
#define smart_environment_DeviceState_sensor_data_distance_MSGTYPE smart_environment_DistanceData

#define smart_environment_LuminosityData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   raw_value,         1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2)
#define smart_environment_LuminosityData_CALLBACK NULL
#define smart_environment_LuminosityData_DEFAULT NULL

#define smart_environment_DistanceData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   distance_cm,       1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2)
#define smart_environment_DistanceData_CALLBACK NULL
#define smart_environment_DistanceData_DEFAULT NULL

extern const pb_msgdesc_t smart_environment_DeviceState_msg;
extern const pb_msgdesc_t smart_environment_LuminosityData_msg;
extern const pb_msgdesc_t smart_environment_DistanceData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define smart_environment_DeviceState_fields &smart_environment_DeviceState_msg
#define smart_environment_LuminosityData_fields &smart_environment_LuminosityData_msg
#define smart_environment_DistanceData_fields &smart_environment_DistanceData_msg

/* Maximum encoded size of messages (where known) */
/* smart_environment_DeviceState_size depends on runtime parameters */
#define SMART_ENVIRONMENT_MESSAGES_PB_H_MAX_SIZE smart_environment_LuminosityData_size
#define smart_environment_DistanceData_size      8
#define smart_environment_LuminosityData_size    8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
